elixir-nebulex/nebulex

- lib/nebulex/adapters/multilevel.ex
When assembling releases using https://github.com/bitwalker/distillery you cannot have references to functions in your config since it can't be translated to a `vm.args` file.
This PR allows you to specify the `:fallback` option as a `{module, function}` tuple instead, which works around the issue.
> Allow fallback to be a {module, function} tuple

- lib/nebulex/adapters/dist.ex
Makes it easier to handle errors.
An alternative would be to document somewhere that the distributed cache can return `{:badrpc, reason}` tuples.
> return error tuple when rpc.call fails

- lib/nebulex/adapters/local.ex
The way it currently works, whenever there's a cache-hit in a previous generation that is copied to the hot cache, the TTL for the item will either be set to `:infinity` or replaced with whatever's currently in `opts`.
This falls back to re-using the TTL unless an override is provided.
> Copy the TTL from the previous generation

- lib/nebulex/adapters/multilevel.ex
I wrote another matching function to catch the :infinity expire_at value and simply pass through the object. This fixes #34.
> Handle an :infinity expiration in multilevel replication.

- mix.exs
When attempting to run a release build of an app that uses Nebulex, trying to start a cache will result in an error that looks something like the following:
```
[info] Application my_app exited: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Cache
** (EXIT) shutdown: failed to start child: MyApp.Cache.ShardsSupervisor
** (EXIT) an exception was raised:
** (UndefinedFunctionError) function :shards_sup.start_link/1 is undefined (module :shards_sup is not available)
:shards_sup.start_link(MyApp.Cache.ShardsSupervisor)
(stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3 
(stdlib) supervisor.erl:365: :supervisor.do_start_child/2
(stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
(stdlib) supervisor.erl:1157: …
```
> Fix error when running in a release

- lib/nebulex/caching.ex
- test/nebulex/caching_test.exs
Sometimes one wants to conditionally cache a value based on the result of the underlying function logic. This is easy to achieve by using the lower-level APIs Cache.get and Cache.set but it is fairly verbose and repeatable. This PR adds a new option to the `Nebulex.Caching` DSL to support it. For example, a classic use case would be avoiding caching the result of a REST API when a transient error is returned.
This PR adds a new option `:match` that takes a function with one argument. The function will be called with the value in the cache and the cache will be updated based on the boolean result returned.
> Add match option to Nebulex.Caching

- lib/nebulex/caching/decorators.ex
> fix: Dialyzer useless control flow

- test/nebulex/adapters/replicated_test.exs
Proves #79 is dead in 65109f3. 
If merged, would ensure #79 _stays_ dead, but I'm not sure that'll be necessary.
> Add test for unflushed messages with exits trapped

- lib/nebulex/caching.ex
- test/nebulex/caching_test.exs
ref issue #111 
I tested the side effect using another cache key on the same cache, any feedback is more than welcome =)
> Avoid calling `cacheable()` method when cached value is `false`

- guides/getting-started.md
- lib/mix/tasks/nbx.gen.cache.ex
- test/mix/tasks/nbx.gen.cache_test.exs
**Issue**
Fix a typo for cache max_size: the comment says it is 1 million, but the number specifies 100,000 (`1_00_000`).
This also generates incorrect config file when using `mix nbx.gen.cache -c`
I assume it's a just typo. But let me know if I should change anything.
> Fix max_size to be actually 1 million instead of 100,000

- lib/nebulex/caching.ex
- test/nebulex/caching_test.exs
This PR enables dynamic cache configuration with decorators:
```elixir
defmodule MyApp.AccountService do
@decorate cacheable(cache: {MyApp.AccountService, :get_cache, []}, key: id)
def get_account(id), do: ...
@decorate cache_put(cache: {MyApp.AccountService, :get_cache, []}, key: account.id)
def update_account(account), do: ...
def get_cache, do: Application.fetch_env!(:my_app, :cache)
end
```
> Allow passing dynamic cache configuration to the decorators

- README.md
There are some differences between using `:pg` and [Horde](https://github.com/derekkraan/horde) to handle in-memory distributed data
This just adds the possibility to use Nebulex taking advantage of Horde process distribution mechanism
All the adapter tests are passing, it would be nice if you could review it too :)
https://github.com/eliasdarruda/nebulex_adapters_horde
> New adapter with Horde

- lib/nebulex/adapters/replicated.ex
See: https://hexdocs.pm/elixir/1.14.1/changelog.html#4-hard-deprecations
> Use import Bitwise instead of use Bitwise

- lib/nebulex/adapters/multilevel.ex
- test/nebulex/adapters/multilevel_concurrency_test.exs
This PR changes the order of delete operations in the Multilevel adapter. Consider the following scenario:
1. Multilevel cache has a stale value
2. Caller A issues a delete request for the key.
3. Multilevel deletes the key from L1
4. At the same time Client B tries to get the key from cache. It finds it in L2 and replicates value to L1.
5. Multilevel delete the key from L2.
So we end up with stale key in L1 after delete.
In order to fix this it would make sense to perform deletes in reverse order, i.e. from L2 to L1. I figured out there are 3 callbacks affected: `delete`, `take` and `delete_all`. 
Please let me know what you think!
> Make Multilevel adapter apply deletes in reverse order

- guides/creating-new-adapter.md
- mix.exs
We've been recently implementing a custom Nebulex adapter and decided to document the process to address https://github.com/cabol/nebulex/issues/96
The guide aims to replicate `NebulexRedisAdapter` setup with adapter being a simple in-memory cache that uses Agent under the hood. Nothing to write home about but should be enough to get anyone started.
Please don't hesitate to correct me on grammar and wording or even completely take over the PR.
> Creating New Adapter guide

- lib/nebulex/adapters/local/generation.ex
- test/nebulex/adapters/local/generation_test.exs
Fix issue https://github.com/cabol/nebulex/issues/182
> fix the crash when gc_interval is not set

- lib/nebulex/adapters/local.ex
- test/nebulex/adapters/local_boolean_keys_test.exs
This fixes a bug in get_all function from Local adapter that was causing keys that are set to 'false' to not be included in the returned map.
It also adds multiple unit tests for Local caches with boolean values.
This is similar to https://github.com/cabol/nebulex/issues/111
> Fix Local.get_all with false values

- lib/nebulex/adapters/multilevel.ex
- test/nebulex/adapters/multilevel_inclusive_test.exs
Fixes a bug in `Nebulex.Adapters.Multilevel.get/3` where values retrieved as `false` is returned as `nil`
> Fix nil check in `Nebulex.Adapters.Multilevel.get/3`

- lib/nebulex/adapters/partitioned.ex
- test/nebulex/adapters/partitioned_test.exs
Thanks for Nebulex!
We've run into a problem using `get_all` when asking for two-item tuple keys (ie `{"foo", 1}`). The partitioned adapter would only consider the first element of the tuple to be the key, and therefore may ask for the data on the wrong node. This seems to have been done to support `put_(new_)all` which puts the key in the first element and values in the second.
I've passed along the action to the `group_keys_by_node` function so we're able to know which structure to expect in the enum.
> Partitioned Adapter supports two-item tuples as keys

- lib/nebulex/caching/decorators.ex
Relying on AST form broke my production today. We've upgraded Elixir to 1.16, but didn't upgrade the Nebulex (and it stayed in 2.5.2). And key_generator started accepting `{module, function, []}` instead of `{module, function, [opts]}` for this very basic decorator:
```
@decorate cacheable(cache: MyCache)
def function(opts) do
...
end
```
FYI: Variables in Elixir are always `{name, _meta, context}` when `name` and `context` are atoms. Pseudo-variables like `__MODULE__` are handled with `"_" <> _` check, but I've also introduced `Macro.special_form?` check, just in case.
You should never rely on metadata (it changed from release to release (like `counter` metadata for variables)) and you can't expect context to always be `nil` for every variable
You can trust me with these things, "I am …
> Improve variable handing in key generators

- README.md
Heyo,
thanks for nebulex! :green_heart: 
just a small thing: Mentioning memcached in the README seems odd as:
* it's not one of the listed adapters
* #22 mentions it and there is an adapter but it seems not actively maintained (last commit 5 years ago): https://github.com/vasuadari/nebulex_memcached_adapter
So I think it's no longer the case and can hence be removed not to confuse people like me :)
> Remove mention of memcached

- lib/nebulex/adapters/partitioned.ex
Bugfix for issue https://github.com/cabol/nebulex/issues/228.
Instead of List.flatten, which will flatten out the lists within the values as well, use Enum.flat_map so only the first level gets flattened and not all the values as well.
> Cache.all(nil, return: :value) did not correctly handle values that are lists.

- lib/nebulex/adapters/multilevel.ex
- test/nebulex/adapters/multilevel_inclusive_test.exs
- test/support/test_cache.ex
This commit fixes a race condition that is likely to happen when one of the layers for a multilevel cache has to do some networking.
The issue arises from the calling `get` to see if a key exists, and then calling `ttl` when replicating the key to other layers. This means that the calls are happening in a non-atomic way, which in turn means that by the time `ttl` gets called the key might have expired already (the race condition).
The fix is detecting that the key has expired by checking for `nil` in the `tll` call result, and in this case not replicating the cached entry to the other layers.
> Fix race condition in multilevel cache replication
